import chai from 'chai';

describe('Replace', function () {
  it('assert.ok is working', function () {
    var before = [
      "$$anonymous$$onoBehaviour",
      "Get$$anonymous$$eyDown",
      "any$$anonymous$$eyDown",
      "ANI$$anonymous$$ATION",
      "$$anonymous$$aterial",
      "$$anonymous$$eyCode",
      "WOR$$anonymous$$ING",
      "Wor$$anonymous$$ing",
      "wor$$anonymous$$ing",
      "EXA$$anonymous$$PLE",
      "$$anonymous$$essage",
      "$$anonymous$$anager",
      "THAN$$anonymous$$S",
      "INS$$anonymous$$D",
      "Ins$$anonymous$$d",
      "ins$$anonymous$$d",
      "$$anonymous$$cher",
      "is$$anonymous$$ey",
      "$$anonymous$$ouse",
      "$$anonymous$$athf",
      "HO$$anonymous$$E",
      "$$anonymous$$ath",
      "$$anonymous$$esh",
      "$$anonymous$$ove",
      "$$anonymous$$ode",
      "$$anonymous$$ost",
      "$$anonymous$$in",
      "$$anonymous$$ax",
      "$$anonymous$$m",
      "$$anonymous$$ey",
      "ND$$anonymous$$",
      "SD$$anonymous$$",
      "AR$$anonymous$$",
      "AP$$anonymous$$",
      "I$$anonymous$$",
      "O$$anonymous$$",
      "$$anonymous$$y",
      "$$anonymous$$",
    ].join(' ');

    var after = [
      "MonoBehaviour",
      "GetKeyDown",
      "anyKeyDown",
      "ANIMATION",
      "Material",
      "KeyCode",
      "WORKING",
      "Working",
      "working",
      "EXAMPLE",
      "Message",
      "Manager",
      "THANKS",
      "INSTEAD",
      "Instead",
      "instead",
      "teacher",
      "isKey",
      "Mouse",
      "Mathf",
      "HOME",
      "Math",
      "Mesh",
      "Move",
      "Mode",
      "Most",
      "Min",
      "Max",
      "team",
      "Key",
      "NDK",
      "SDK",
      "ARM",
      "APK",
      "IK",
      "OK",
      "My",
      "M",
    ].join(' ');

    chai.assert.equal(before, after);
  });
});
